version: '3.8'
services:
  # postgres:
  #   image: postgres:15
  #   container_name: postgres-container
  #   environment:
  #     POSTGRES_USER: votre_utilisateur
  #     POSTGRES_PASSWORD: mot_de_passe
  #     POSTGRES_DB: cloud
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - spring-network

  spring-boot-app:
    build:
      context: .
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - postgres

networks:
  spring-network:
    driver: bridge
